CREATE TABLE users (
   id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   user_role VARCHAR(20) NOT NULL,
   user_name VARCHAR(50) NOT NULL,
   email VARCHAR(30) NOT NULL,
   password VARCHAR(20) NOT NULL,
   phone_number VARCHAR(20) NULL,
   created_at TIMESTAMP NOT NULL,
   updated_at TIMESTAMP NULL
)
