CREATE TABLE order_item (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	order_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	price INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL
)
