version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spring_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_db
    volumes:
      - ecommerce_monolithic_mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: spring_redis
    ports:
      - "6379:6379"
    volumes:
      - ecommerce_monolithic_redis_data:/data
    restart: always

volumes:
  ecommerce_monolithic_mysql_data:
  ecommerce_monolithic_redis_data:
