version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spring_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_db
    volumes:
      - ecommerce_monolithic_mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  ecommerce_monolithic_mysql_data:
